FROM almalinux:9
ARG course="docker" \
    duration="120hrs"
RUN echo "Course:$course , Duration:$duration"
CMD ["sleep", "100"]


# ARG version
# FROM almalinux:${version:-9}
# ARG course="docker" \
#     duration="120hrs"
# RUN echo "Course:$course , Duration:$duration"
# CMD ["sleep", "100"]
